// <auto-generated />
using System;
using Andon.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Andon.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601112106_InitialAndonSchema")]
    partial class InitialAndonSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Andon.Web.Models.Domain.ActionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AssignedDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("AssignedPrincipalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("AssignedPrincipalType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ClosureComment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ContextSnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CreatedByPrincipalType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ExternalProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ExternalRcaIncidentId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid?>("ExternalTaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<long?>("RelatedAndonAlertId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TaskSnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RelatedAndonAlertId");

                    b.HasIndex("TenantId", "ExternalRcaIncidentId");

                    b.HasIndex("TenantId", "RelatedAndonAlertId");

                    b.HasIndex("TenantId", "ExternalTaskId", "Status");

                    b.HasIndex("TenantId", "Status", "DueDate");

                    b.HasIndex("TenantId", "AssignedPrincipalType", "AssignedPrincipalId", "Status");

                    b.ToTable("action_items", (string)null);
                });

            modelBuilder.Entity("Andon.Web.Models.Domain.AndonAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AcknowledgedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("AssignedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContextSnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CreatedByPrincipalType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("EscalatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ExternalProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ExternalRcaIncidentId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid?>("ExternalTaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("OpenedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("OperationalEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RcaCreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RcaStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ResolutionComment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponsibleDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ResponsiblePrincipalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ResponsiblePrincipalType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TaskSnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("OperationalEventId");

                    b.HasIndex("TenantId", "ExternalRcaIncidentId");

                    b.HasIndex("TenantId", "ExternalTaskId", "Status");

                    b.HasIndex("TenantId", "MachineId", "Status");

                    b.HasIndex("TenantId", "Severity", "Status");

                    b.HasIndex("TenantId", "Status", "OpenedUtc");

                    b.ToTable("andon_alerts", (string)null);
                });

            modelBuilder.Entity("Andon.Web.Models.Domain.AndonComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AndonAlertId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("CreatedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CreatedByPrincipalType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AndonAlertId");

                    b.HasIndex("TenantId", "AndonAlertId", "CreatedUtc");

                    b.ToTable("andon_comments", (string)null);
                });

            modelBuilder.Entity("Andon.Web.Models.Domain.OperationalEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ContextSnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CreatedByPrincipalType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid?>("ExternalProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ExternalTaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("TaskSnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExternalTaskId");

                    b.HasIndex("TenantId", "OccurredUtc");

                    b.HasIndex("TenantId", "MachineId", "OccurredUtc");

                    b.HasIndex("TenantId", "Severity", "OccurredUtc");

                    b.HasIndex("TenantId", "Source", "EventType");

                    b.ToTable("operational_events", (string)null);
                });

            modelBuilder.Entity("Andon.Web.Models.Domain.ActionItem", b =>
                {
                    b.HasOne("Andon.Web.Models.Domain.AndonAlert", "RelatedAndonAlert")
                        .WithMany("ActionItems")
                        .HasForeignKey("RelatedAndonAlertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedAndonAlert");
                });

            modelBuilder.Entity("Andon.Web.Models.Domain.AndonAlert", b =>
                {
                    b.HasOne("Andon.Web.Models.Domain.OperationalEvent", "OperationalEvent")
                        .WithMany("AndonAlerts")
                        .HasForeignKey("OperationalEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OperationalEvent");
                });

            modelBuilder.Entity("Andon.Web.Models.Domain.AndonComment", b =>
                {
                    b.HasOne("Andon.Web.Models.Domain.AndonAlert", "AndonAlert")
                        .WithMany("Comments")
                        .HasForeignKey("AndonAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AndonAlert");
                });

            modelBuilder.Entity("Andon.Web.Models.Domain.AndonAlert", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Andon.Web.Models.Domain.OperationalEvent", b =>
                {
                    b.Navigation("AndonAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
